// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:chatapp/graphql/__generated__/schema.schema.gql.dart'
    show
        GAccountStatus,
        GAddKnowledgeBaseItemInput,
        GAddReviewInput,
        GAgentSort,
        GAgentStatus,
        GAgentType,
        GAgentUi,
        GApproveCommentInput,
        GApproveDraftInput,
        GAudienceKnowledgeLevel,
        GBrandVoiceTone,
        GCaptchaToken,
        GCaptchaVersion,
        GCategory,
        GChangePasswordInput,
        GChatAuthorRole,
        GChatJobStatus,
        GChatbotStatus,
        GCommentReviewStatus,
        GConfirmResetPasswordInput,
        GContentFormat,
        GCreateChatInput,
        GCreateChatbotInput,
        GCreateMiniAgentInput,
        GCreateSeoEcommercePresetInput,
        GCurrency,
        GDoModelStatus,
        GDraftStatus,
        GFeature,
        GFinishMiniAgentDraftInput,
        GGenerateEcommerceContentInput,
        GGetopenpayCheckoutSessionInput,
        GGetopenpayPriceEnv,
        GGetopenpaySessionStatus,
        GGetopenpaySubscriptionStatus,
        GGoogleAuthPlatform,
        GKnowledgeBaseSourceType,
        GKnowledgeBaseStatus,
        GLeaveCommentInput,
        GLoginViaEmailInput,
        GModel,
        GModelProvider,
        GOpType,
        GPaymentInterval,
        GPaymentProvider,
        GPriceStatus,
        GProductType,
        GRegisterViaEmailInput,
        GRegisterViaGoogleInput,
        GRegistrationType,
        GRejectCommentInput,
        GRejectDraftInput,
        GResponseType,
        GRole,
        GRunCurrency,
        GSendEmailInput,
        GSeoEcommerceRequestStatus,
        GStartGetopenpayTrialInput,
        GStartUploadToAgentDraftInput,
        GStartUploadToChatInput,
        GStripeCheckoutSessionInput,
        GStripePriceEnv,
        GStripeSessionStatus,
        GStripeSubscriptionStatus,
        GSubscriptionSchedulePeriod,
        GSubscriptionScheduleStatus,
        GSubscriptionScheduleType,
        GSubscriptionStatus,
        GTargetType,
        GTargetWordCount,
        GTime,
        GTrialRunCurrency,
        GTxDirection,
        GTxStatus,
        GTxType,
        GUpdateChatbotInput,
        GUpdateEmailPreferences,
        GUpdateMiniAgentDraftInput,
        GUpdateMiniAgentInput,
        GUpload,
        GUuid,
        GVendor,
        GVisibility,
        GVoid,
        GWebSearchStatus;
import 'package:chatapp/graphql/operations/__generated__/auth.data.gql.dart'
    show
        GLoginData,
        GLoginData_loginViaEmail,
        GRefreshTokenData,
        GRefreshTokenData_refreshToken;
import 'package:chatapp/graphql/operations/__generated__/auth.req.gql.dart'
    show GLoginReq, GRefreshTokenReq;
import 'package:chatapp/graphql/operations/__generated__/auth.var.gql.dart'
    show GLoginVars, GRefreshTokenVars;
import 'package:chatapp/graphql/operations/__generated__/user.data.gql.dart'
    show GMeData, GMeData_me, GMeData_me_balance;
import 'package:chatapp/graphql/operations/__generated__/user.req.gql.dart'
    show GMeReq;
import 'package:chatapp/graphql/operations/__generated__/user.var.gql.dart'
    show GMeVars;
import 'package:ferry_exec/ferry_exec.dart';
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAccountStatus,
  GAddKnowledgeBaseItemInput,
  GAddReviewInput,
  GAgentSort,
  GAgentStatus,
  GAgentType,
  GAgentUi,
  GApproveCommentInput,
  GApproveDraftInput,
  GAudienceKnowledgeLevel,
  GBrandVoiceTone,
  GCaptchaToken,
  GCaptchaVersion,
  GCategory,
  GChangePasswordInput,
  GChatAuthorRole,
  GChatJobStatus,
  GChatbotStatus,
  GCommentReviewStatus,
  GConfirmResetPasswordInput,
  GContentFormat,
  GCreateChatInput,
  GCreateChatbotInput,
  GCreateMiniAgentInput,
  GCreateSeoEcommercePresetInput,
  GCurrency,
  GDoModelStatus,
  GDraftStatus,
  GFeature,
  GFinishMiniAgentDraftInput,
  GGenerateEcommerceContentInput,
  GGetopenpayCheckoutSessionInput,
  GGetopenpayPriceEnv,
  GGetopenpaySessionStatus,
  GGetopenpaySubscriptionStatus,
  GGoogleAuthPlatform,
  GKnowledgeBaseSourceType,
  GKnowledgeBaseStatus,
  GLeaveCommentInput,
  GLoginData,
  GLoginData_loginViaEmail,
  GLoginReq,
  GLoginVars,
  GLoginViaEmailInput,
  GMeData,
  GMeData_me,
  GMeData_me_balance,
  GMeReq,
  GMeVars,
  GModel,
  GModelProvider,
  GOpType,
  GPaymentInterval,
  GPaymentProvider,
  GPriceStatus,
  GProductType,
  GRefreshTokenData,
  GRefreshTokenData_refreshToken,
  GRefreshTokenReq,
  GRefreshTokenVars,
  GRegisterViaEmailInput,
  GRegisterViaGoogleInput,
  GRegistrationType,
  GRejectCommentInput,
  GRejectDraftInput,
  GResponseType,
  GRole,
  GRunCurrency,
  GSendEmailInput,
  GSeoEcommerceRequestStatus,
  GStartGetopenpayTrialInput,
  GStartUploadToAgentDraftInput,
  GStartUploadToChatInput,
  GStripeCheckoutSessionInput,
  GStripePriceEnv,
  GStripeSessionStatus,
  GStripeSubscriptionStatus,
  GSubscriptionSchedulePeriod,
  GSubscriptionScheduleStatus,
  GSubscriptionScheduleType,
  GSubscriptionStatus,
  GTargetType,
  GTargetWordCount,
  GTime,
  GTrialRunCurrency,
  GTxDirection,
  GTxStatus,
  GTxType,
  GUpdateChatbotInput,
  GUpdateEmailPreferences,
  GUpdateMiniAgentDraftInput,
  GUpdateMiniAgentInput,
  GUpload,
  GUuid,
  GVendor,
  GVisibility,
  GVoid,
  GWebSearchStatus,
])
final Serializers serializers = _serializersBuilder.build();
