// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.gql.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(FetchPolicy.serializer)
      ..add(GAccountStatus.serializer)
      ..add(GAddKnowledgeBaseItemInput.serializer)
      ..add(GAddReviewInput.serializer)
      ..add(GAgentSort.serializer)
      ..add(GAgentStatus.serializer)
      ..add(GAgentType.serializer)
      ..add(GAgentUi.serializer)
      ..add(GApproveCommentInput.serializer)
      ..add(GApproveDraftInput.serializer)
      ..add(GAudienceKnowledgeLevel.serializer)
      ..add(GBrandVoiceTone.serializer)
      ..add(GCaptchaToken.serializer)
      ..add(GCaptchaVersion.serializer)
      ..add(GCategory.serializer)
      ..add(GChangePasswordInput.serializer)
      ..add(GChatAuthorRole.serializer)
      ..add(GChatJobStatus.serializer)
      ..add(GChatbotStatus.serializer)
      ..add(GCommentReviewStatus.serializer)
      ..add(GConfirmResetPasswordInput.serializer)
      ..add(GContentFormat.serializer)
      ..add(GCreateChatInput.serializer)
      ..add(GCreateChatbotInput.serializer)
      ..add(GCreateMiniAgentInput.serializer)
      ..add(GCreateSeoEcommercePresetInput.serializer)
      ..add(GCurrency.serializer)
      ..add(GDoModelStatus.serializer)
      ..add(GDraftStatus.serializer)
      ..add(GFeature.serializer)
      ..add(GFinishMiniAgentDraftInput.serializer)
      ..add(GGenerateEcommerceContentInput.serializer)
      ..add(GGetopenpayCheckoutSessionInput.serializer)
      ..add(GGetopenpayPriceEnv.serializer)
      ..add(GGetopenpaySessionStatus.serializer)
      ..add(GGetopenpaySubscriptionStatus.serializer)
      ..add(GGoogleAuthPlatform.serializer)
      ..add(GKnowledgeBaseSourceType.serializer)
      ..add(GKnowledgeBaseStatus.serializer)
      ..add(GLeaveCommentInput.serializer)
      ..add(GLoginData.serializer)
      ..add(GLoginData_loginViaEmail.serializer)
      ..add(GLoginReq.serializer)
      ..add(GLoginVars.serializer)
      ..add(GLoginViaEmailInput.serializer)
      ..add(GMeData.serializer)
      ..add(GMeData_me.serializer)
      ..add(GMeData_me_balance.serializer)
      ..add(GMeReq.serializer)
      ..add(GMeVars.serializer)
      ..add(GModel.serializer)
      ..add(GModelProvider.serializer)
      ..add(GOpType.serializer)
      ..add(GPaymentInterval.serializer)
      ..add(GPaymentProvider.serializer)
      ..add(GPriceStatus.serializer)
      ..add(GProductType.serializer)
      ..add(GRefreshTokenData.serializer)
      ..add(GRefreshTokenData_refreshToken.serializer)
      ..add(GRefreshTokenReq.serializer)
      ..add(GRefreshTokenVars.serializer)
      ..add(GRegisterViaEmailInput.serializer)
      ..add(GRegisterViaGoogleInput.serializer)
      ..add(GRegistrationType.serializer)
      ..add(GRejectCommentInput.serializer)
      ..add(GRejectDraftInput.serializer)
      ..add(GResponseType.serializer)
      ..add(GRole.serializer)
      ..add(GRunCurrency.serializer)
      ..add(GSendEmailInput.serializer)
      ..add(GSeoEcommerceRequestStatus.serializer)
      ..add(GStartGetopenpayTrialInput.serializer)
      ..add(GStartUploadToAgentDraftInput.serializer)
      ..add(GStartUploadToChatInput.serializer)
      ..add(GStripeCheckoutSessionInput.serializer)
      ..add(GStripePriceEnv.serializer)
      ..add(GStripeSessionStatus.serializer)
      ..add(GStripeSubscriptionStatus.serializer)
      ..add(GSubscriptionSchedulePeriod.serializer)
      ..add(GSubscriptionScheduleStatus.serializer)
      ..add(GSubscriptionScheduleType.serializer)
      ..add(GSubscriptionStatus.serializer)
      ..add(GTargetType.serializer)
      ..add(GTargetWordCount.serializer)
      ..add(GTime.serializer)
      ..add(GTrialRunCurrency.serializer)
      ..add(GTxDirection.serializer)
      ..add(GTxStatus.serializer)
      ..add(GTxType.serializer)
      ..add(GUpdateChatbotInput.serializer)
      ..add(GUpdateEmailPreferences.serializer)
      ..add(GUpdateMiniAgentDraftInput.serializer)
      ..add(GUpdateMiniAgentInput.serializer)
      ..add(GUpload.serializer)
      ..add(GUuid.serializer)
      ..add(GVendor.serializer)
      ..add(GVisibility.serializer)
      ..add(GVoid.serializer)
      ..add(GWebSearchStatus.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => new ListBuilder<String>()))
    .build();

// ignore_for_file: deprecated_member_use_from_same_package,type=lint
